apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
        - image: thangtq14/udagram-frontend:v1
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: configuration-values
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: configuration-values
                  key: AWS_PROFILE
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: configuration-values
                  key: AWS_BUCKET
      restartPolicy: Always
