name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t udagram-reverseproxy ./udagram-reverseproxy
          docker build -t udagram-api-feed ./udagram-api-feed
          docker build -t udagram-api-user ./udagram-api-user
          docker build -t udagram-frontend ./udagram-frontend
      
      - name: Tag Docker image
        run: |
          docker tag udagram-reverseproxy thangtq14/reverseproxy:v1
          docker tag udagram-api-feed thangtq14/udagram-api-feed:v1
          docker tag udagram-api-user thangtq14/udagram-api-user:v1
          docker tag udagram-frontend thangtq14/udagram-frontend:v1
      
      - name: Push Docker image
        run: |
          docker push thangtq14/reverseproxy:v1
          docker push thangtq14/udagram-api-feed:v1
          docker push thangtq14/udagram-api-user:v1
          docker push thangtq14/udagram-frontend:v1
